### ISSUE TITLE
IntelliJ 2016.2 problems

### ISSUE THREAD

**Issue by mjiderhamn** [SmartBear/idea-collaborator-plugin#3]
In IntelliJ 2016.2 and 2016.2.2, when clicking the Finish button in the "Add Commits to Review" dialog, there is an error. First try results in:

```
loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of com/intellij/ide/plugins/cl/PluginClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of com/intellij/util/lang/UrlClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of com/intellij/ide/plugins/cl/PluginClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of com/intellij/util/lang/UrlClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
    at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:299)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
    at org.eclipse.jgit.util.FS.<clinit>(FS.java:112)
    at org.eclipse.jgit.lib.BaseRepositoryBuilder.safeFS(BaseRepositoryBuilder.java:730)
    at org.eclipse.jgit.lib.BaseRepositoryBuilder.findGitDir(BaseRepositoryBuilder.java:511)
    at com.smartbear.collab.util.ChangeListUtils.VcsFileRevisionToChangeList(ChangeListUtils.java:105)
    at com.smartbear.collab.plugin.review.ui.AddCommitsToReview.onFinish(AddCommitsToReview.java:173)
    at com.smartbear.collab.plugin.review.ui.AddCommitsToReview.access$100(AddCommitsToReview.java:19)
    at com.smartbear.collab.plugin.review.ui.AddCommitsToReview$2.actionPerformed(AddCommitsToReview.java:59)
...
```

Subsequent tries result in:

```
Could not initialize class org.eclipse.jgit.util.FS
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.jgit.util.FS
    at org.eclipse.jgit.lib.BaseRepositoryBuilder.safeFS(BaseRepositoryBuilder.java:730)
    at org.eclipse.jgit.lib.BaseRepositoryBuilder.findGitDir(BaseRepositoryBuilder.java:511)
    at com.smartbear.collab.util.ChangeListUtils.VcsFileRevisionToChangeList(ChangeListUtils.java:105)
    at com.smartbear.collab.plugin.review.ui.AddCommitsToReview.onFinish(AddCommitsToReview.java:173)
    at com.smartbear.collab.plugin.review.ui.AddCommitsToReview.access$100(AddCommitsToReview.java:19)
    at com.smartbear.collab.plugin.review.ui.AddCommitsToReview$2.actionPerformed(AddCommitsToReview.java:59)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
...
```

**Comment by mjiderhamn** [comment]
The workaround seems to be to remove `slf4j-api-1.7.2.jar` (IntelliJ already contains version 1.7.10)

**Comment by NikitaMishin** [comment]
same works for me
