### ISSUE TITLE
NPE  on "Add to Review" Idea 2016.2.4

### ISSUE THREAD

**Issue by repli007** [SmartBear/idea-collaborator-plugin#4]
Idea 2016.2.4
After click of searched in actions "Add to Review" -
`null
java.lang.NullPointerException
 at com.smartbear.collab.plugin.review.ReviewFromScmHistory.actionPerformed(ReviewFromScmHistory.java:30)
 at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
 at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
 at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
 at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
 at com.intellij.ide.actions.GotoActionAction.lambda$performAction$1(GotoActionAction.java:273)
 at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
 at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
 at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:73)
 at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
 at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:793)
 at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:629)
 at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by volkadav** [comment]
Hi, thank you for the issue report!  I've actually left the project, but I will reach out to the person running the tech team there about this.

**Comment by repli007** [comment]
Many thanks!
